services:

  docs-db:
    image: postgres:15
    container_name: docs-db

    environment:
      POSTGRES_DB: docsdb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  docs-backend:
    build: .
    container_name: docs-backend

    depends_on:
      - docs-db

    ports:
      - "8081:8081"

    environment:
      DB_URL: jdbc:postgresql://docs-db:5432/docsdb
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}

volumes:
  postgres_data: