# =========================
# Database - Development
# =========================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/docsdb}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# =========================
# JPA / Hibernate
# =========================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false


# =========================
# Logging - Development
# =========================

logging.file.name=logs/dev-app.log

logging.level.root=INFO
logging.level.com.docs=DEBUG

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] [%X{requestId}] %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss} [%level] [%X{requestId}] %logger - %msg%n

# =========================
# JWT - Development
# =========================

app.jwt.secret=${JWT_SECRET}